import { useState } from 'react';
import { X, Plus, Trash2, Loader2, AlertCircle, CheckCircle2, Download, FlaskConical, Dices, DatabaseZap } from 'lucide-react';
import { insertRowsIntoFabricTable, fetchFabricInsertJob } from '../../api';
import { useConfirm } from '../common/confirmContext';
import { pollJob } from '../../pollJob';

const INITIAL_ROW_COUNT = 25;

// However many rows the tester asks for (up to 100,000) actually get
// generated and pushed - this cap only limits how many get rendered as
// individually-editable <input> cells, since a browser tab hand-editing
// 100,000 rows of <input> elements would lock up regardless of how fast the
// generation logic itself is. Rows beyond this are still generated by "Add
// random values" and included in the download/insert, just not individually
// hand-editable.
const MAX_EDITABLE_ROWS = 200;
const ROW_COUNT_OPTIONS = [25, 50, 75, 100, 250, 500, 1000, 2500, 5000, 10000, 25000, 50000, 100000];

const emptyRow = (columns) => Object.fromEntries(columns.map((c) => [c.name, '']));

// Pure client-side generation - not AI, no inference from real data (there
// is none to learn from: this feature's whole point is that a tester never
// sees real rows). First pass just typed the cell by its DuckDB TYPE, which
// produced correctly-shaped but meaningless gibberish (a VARCHAR "email"
// column got "kPFKdejY") - confusing rather than helpful, since nothing
// about it reads as the kind of value that column actually holds. This
// version also looks at the COLUMN NAME, so an "email" column gets an
// email-shaped fake address, a "city" column gets a real city name, etc. -
// still 100% fake, just fake in a way that doesn't require the tester to
// first decode what a value is supposed to represent before editing it.
const randomInt = (min, max) => Math.floor(Math.random() * (max - min + 1)) + min;
const pick = (arr) => arr[randomInt(0, arr.length - 1)];

const FIRST_NAMES = ['James', 'Mary', 'John', 'Patricia', 'Robert', 'Jennifer', 'Michael', 'Linda',
  'David', 'Elizabeth', 'William', 'Barbara', 'Ava', 'Noah', 'Olivia', 'Liam', 'Emma', 'Sophia', 'Mason', 'Isabella'];
const LAST_NAMES = ['Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia', 'Miller', 'Davis',
  'Rodriguez', 'Martinez', 'Wilson', 'Anderson', 'Taylor', 'Thomas', 'Moore', 'Jackson', 'Martin', 'Lee'];
const STREETS = ['Main St', 'Oak Ave', 'Maple Dr', 'Cedar Ln', 'Park Blvd', 'Elm St', 'Washington Ave', 'Lake Rd'];
const CITIES = ['Delhi', 'Riverside', 'Ahmedabad', 'Greenville', 'Mumbai', 'Fairview', 'Salem', 'Madison', 'Bengaluru', 'Dallas', 'Chennai','New Austin', 'Kolkata'];
const STATES = ['California', 'Texas', 'New York', 'Ontario', 'Bavaria', 'Queensland', 'Maharashtra'];
const COUNTRIES = ['USA', 'UK', 'India', 'Canada', 'Germany', 'Australia'];
const DEPARTMENTS = ['Engineering', 'Sales', 'Marketing', 'Finance', 'HR','Legal', 'Operations', 'Support'];
const STATUSES = ['Active', 'Pending', 'Closed', 'Inactive', 'Completed'];
const NOTES = ['Looks good', 'Needs review', 'Pending confirmation', 'No issues found', 'Follow-up required'];
const DOMAINS = ['example.com', 'mail.com', 'test.org', 'sample.net'];
const GENERIC_WORDS = ['Alpha', 'Beta', 'Delta', 'Sigma', 'Nova', 'Prime', 'Vertex', 'Atlas', 'Echo', 'Orbit'];

function randomDate() {
  const start = new Date(2020, 0, 1).getTime();
  const end = new Date(2026, 11, 31).getTime();
  return new Date(start + Math.random() * (end - start)).toISOString().slice(0, 10);
}

function randomTime() {
  const p2 = (n) => String(n).padStart(2, '0');
  return `${p2(randomInt(0, 23))}:${p2(randomInt(0, 59))}:${p2(randomInt(0, 59))}`;
}

function randomUuid() {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = randomInt(0, 15);
    return (c === 'x' ? r : (r & 0x3) | 0x8).toString(16);
  });
}

/**
 * Value shaped by what the COLUMN NAME suggests it holds - checked before
 * falling back to a type-only guess, since the name is almost always the
 * stronger signal for a VARCHAR/TEXT column (the type alone can't tell
 * "email" apart from "city"). Returns null when nothing matches, so the
 * caller falls back to a generic-but-still-word-like filler instead of
 * raw character noise.
 */
function semanticStringValue(columnName) {
  const n = (columnName || '').toLowerCase();
  if (/(email)/.test(n)) return `${pick(FIRST_NAMES).toLowerCase()}.${pick(LAST_NAMES).toLowerCase()}${randomInt(1, 99)}@${pick(DOMAINS)}`;
  if (/(first.?name|given.?name)/.test(n)) return pick(FIRST_NAMES);
  if (/(last.?name|surname|family.?name)/.test(n)) return pick(LAST_NAMES);
  if (/(full.?name|^name$|customer.?name|employee.?name|staff.?name|contact.?name|student.?name)/.test(n)) {
    return `${pick(FIRST_NAMES)} ${pick(LAST_NAMES)}`;
  }
  // Checked before the generic "date" pattern below, since "datetime"/
  // "timestamp" both also contain/imply a date and would otherwise match
  // that broader check first and lose the time-of-day half.
  if (/(datetime|timestamp)/.test(n)) return `${randomDate()} ${randomTime()}`;
  // Catches date-ish VARCHAR/TEXT columns whose declared TYPE is generic
  // (common for CSV-sourced tables, where every column comes back as plain
  // VARCHAR regardless of what it actually holds) - without this, a column
  // like "start_date" fell through every check here and got the same
  // generic word+number filler as a column with no discernible meaning at
  // all, which reads as nonsense for something that's clearly a date.
  if (/(date|_dob$|^dob$|birthdate|anniversary)/.test(n)) return randomDate();
  if (/(^|_)time$/.test(n)) return randomTime();
  if (/(phone|mobile|telephone)/.test(n)) return `+1-${randomInt(200, 999)}-${randomInt(200, 999)}-${String(randomInt(0, 9999)).padStart(4, '0')}`;
  if (/(street|address.?line)/.test(n)) return `${randomInt(1, 9999)} ${pick(STREETS)}`;
  if (/(city|district|town)/.test(n)) return pick(CITIES);
  if (/(zip|postal|pin.?code)/.test(n)) return String(randomInt(10000, 99999));
  if (/country/.test(n)) return pick(COUNTRIES);
  if (/(state|province)/.test(n)) return pick(STATES);
  if (/status/.test(n)) return pick(STATUSES);
  if (/(url|website|link|site)/.test(n)) return `https://www.${pick(GENERIC_WORDS).toLowerCase()}.com`;
  if (/(department|^dept$)/.test(n)) return pick(DEPARTMENTS);
  if (/(company|organi[sz]ation|employer)/.test(n)) return `${pick(LAST_NAMES)} ${pick(['Inc', 'LLC', 'Corp', 'Group', 'Co'])}`;
  if (/(description|note|comment|remark)/.test(n)) return pick(NOTES);
  if (/(^id$|.?_id$|code|reference|ref)$/.test(n)) return `${n.slice(0, 3).toUpperCase()}-${randomInt(1000, 9999)}`;
  return null;
}

function randomValueForType(column) {
  const t = (column.data_type || '').toUpperCase();
  if (/^(BOOLEAN|BOOL)$/.test(t)) return Math.random() < 0.5 ? 'true' : 'false';
  if (/^DECIMAL/.test(t)) {
    const m = t.match(/DECIMAL\(\s*\d+\s*,\s*(\d+)\s*\)/);
    const scale = m ? parseInt(m[1], 10) : 2;
    return (Math.random() * 1000).toFixed(scale);
  }
  if (/^(FLOAT|DOUBLE|REAL)$/.test(t)) return (Math.random() * 1000).toFixed(2);
  if (/^(TINYINT|SMALLINT|INTEGER|BIGINT|HUGEINT|UTINYINT|USMALLINT|UINTEGER|UBIGINT)$/.test(t)) {
    return String(randomInt(1, 10000));
  }
  if (/^UUID$/.test(t)) return randomUuid();
  if (/^DATE$/.test(t)) return randomDate();
  // TIMESTAMP checked before TIME: "TIMESTAMP" also matches /^TIME/, so
  // checking TIME first would silently truncate every timestamp down to
  // just a time-of-day, dropping the date half entirely.
  if (/^TIMESTAMP/.test(t)) return `${randomDate()} ${randomTime()}`;
  if (/^TIME/.test(t)) return randomTime();
  // VARCHAR/TEXT/BLOB/anything unrecognized: try the column name first, and
  // only fall back to a generic word+number filler ("Nova42") - never raw
  // character noise - when the name gives no hint at all.
  return semanticStringValue(column.name) || `${pick(GENERIC_WORDS)}${randomInt(1, 99)}`;
}

const randomRow = (columns) => Object.fromEntries(columns.map((c) => [c.name, randomValueForType(c)]));

// Generated test data is client-side only now - no backend table is ever
// created for it, so "download" just means "build a CSV from the finalized
// draft rows and hand it to the browser". Previously this named the file
// after an opaque server-generated id ("5n45hiu436354hj5_...csv"), which told
// a tester nothing about which table or which run it came from. This builds
// a readable name instead: the source table + a same-second timestamp, so a
// tester who regenerates a few times can tell versions apart at a glance.
function csvCell(value) {
  const s = String(value ?? '');
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

function buildCsv(columns, rows) {
  const header = columns.map((c) => csvCell(c.name)).join(',');
  const body = rows.map((r) => columns.map((c) => csvCell(r[c.name])).join(',')).join('\n');
  return `${header}\n${body}\n`;
}

function timestampedCsvFilename(sourceTableName) {
  const safeName = (sourceTableName || 'table').replace(/[^a-zA-Z0-9]+/g, '_').replace(/^_+|_+$/g, '') || 'table';
  const now = new Date();
  const p2 = (n) => String(n).padStart(2, '0');
  const stamp = `${now.getFullYear()}${p2(now.getMonth() + 1)}${p2(now.getDate())}_${p2(now.getHours())}${p2(now.getMinutes())}${p2(now.getSeconds())}`;
  return `test_data_${safeName}_${stamp}.csv`;
}

function downloadCsv(filename, csvText) {
  const blob = new Blob([csvText], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

/**
 * Draft-then-finalize flow for a personal synthetic test table.
 *
 * Nothing is created until Finalize is pressed - everything before that is
 * pure local state. The tester picked a real table's SCHEMA (columns/types
 * only, never real rows - `source.columns` came from the same live schema
 * fetch the rest of the app already trusts) as a template; they fill in
 * however many rows they actually want, add/remove freely, then Finalize
 * writes it into their personal test-data connector in one shot.
 */
export default function TestDataDraftModal({ source, onClose, onCreated }) {
  const confirm = useConfirm();
  const [rowCount, setRowCount] = useState(INITIAL_ROW_COUNT);
  const [rows, setRows] = useState(() =>
    Array.from({ length: INITIAL_ROW_COUNT }, () => emptyRow(source.columns)));
  const [error, setError] = useState(null);
  const [result, setResult] = useState(null); // { rowCount } - set once Finalize builds+downloads the CSV
  const [isInserting, setIsInserting] = useState(false);
  const [insertStatus, setInsertStatus] = useState(null); // Fabric job status text while polling

  const updateCell = (rowIndex, colName, value) => {
    setRows((rs) => rs.map((r, i) => (i === rowIndex ? { ...r, [colName]: value } : r)));
  };

  // Changing the row-count picker replaces the draft with a fresh blank set
  // at the new size - simple and safe since nothing is written anywhere
  // until Finalize (same "pure local state until confirmed" rule the rest of
  // this modal already follows).
  const changeRowCount = (n) => {
    setRowCount(n);
    setRows(Array.from({ length: n }, () => emptyRow(source.columns)));
  };

  const addRow = () => setRows((rs) => [...rs, emptyRow(source.columns)]);
  const removeRow = (rowIndex) => setRows((rs) => rs.filter((_, i) => i !== rowIndex));
  const randomizeRow = (rowIndex) => setRows((rs) => rs.map((r, i) => (i === rowIndex ? randomRow(source.columns) : r)));
  // Fills every row - not just the blank ones - so one click gives a
  // complete, type-shaped starting dataset regardless of anything already
  // typed. Cheap to redo: click again for a fresh set, or hand-edit
  // individual cells afterward for the specific pass/fail values that
  // actually matter to the check being tested.
  const randomizeAllRows = () => setRows((rs) => rs.map(() => randomRow(source.columns)));

  // Rows that are still entirely blank aren't sent - a tester who asked for
  // 25 starting rows and only filled in 6 almost certainly means 6, not 25
  // rows of empty strings.
  const nonEmptyRows = rows.filter((r) => Object.values(r).some((v) => String(v ?? '').trim() !== ''));

  // Nothing is created server-side anymore - Finalize just builds a CSV from
  // the finalized draft rows and downloads it immediately. The tester owns
  // the file from here (uploads it wherever they need it themselves).
  const handleFinalize = () => {
    if (nonEmptyRows.length === 0) { setError('Fill in at least one row first'); return; }
    setError(null);
    downloadCsv(timestampedCsvFilename(source.tableName), buildCsv(source.columns, nonEmptyRows));
    setResult({ rowCount: nonEmptyRows.length });
    // Handed up so the table row's own "Push to Fabric" button (which stays
    // disabled until a table has generated data) has something to push
    // without needing this modal open at all - see PipelinesPage's
    // generatedTestData cache.
    onCreated?.({ tableName: source.tableName, columns: source.columns, rows: nonEmptyRows });
  };

  const handleDownloadAgain = () => {
    downloadCsv(timestampedCsvFilename(source.tableName), buildCsv(source.columns, nonEmptyRows));
  };

  // The one real write path this modal offers - deliberately separate from
  // Finalize/Download, and gated behind an explicit danger-toned confirm
  // naming the exact target and row count on top of the backend's own
  // confirm flag, since this writes fake rows directly into a REAL Fabric
  // table with no undo. Fabric's SQL endpoint can't run DML against a
  // Lakehouse table at all (a hard platform limit - see api.js), so this
  // submits a Spark notebook job and polls it rather than getting an
  // immediate row count back; a cold Spark start commonly takes a couple of
  // minutes before the insert itself even begins.
  const handleInsertIntoFabric = async () => {
    const ok = await confirm(
      `Insert ${nonEmptyRows.length} generated row${nonEmptyRows.length === 1 ? '' : 's'} directly into the real ` +
        `Fabric table "${source.tableName}"? This runs a Fabric notebook job and can take a few minutes. ` +
        `This cannot be undone from here - only proceed if that table is meant to receive test data.`,
      { confirmLabel: 'Insert rows', tone: 'danger' },
    );
    if (!ok) return;
    setIsInserting(true);
    setError(null);
    setInsertStatus('Starting the Fabric notebook job…');
    try {
      const started = await insertRowsIntoFabricTable(source.connectorId, {
        containerId: source.containerId,
        tableName: source.tableName,
        rows: nonEmptyRows,
      });
      const run = await pollJob(
        () => fetchFabricInsertJob(source.connectorId, started.notebook_item_id, started.job_id, {
          containerId: started.container_id, stagingPath: started.staging_path,
          tableName: source.tableName, rowCount: started.row_count,
        }),
        { onTick: (r) => setInsertStatus(r.is_running ? 'Running in Fabric… (Spark can take a few minutes to start)' : null) },
      );
      if (run.status !== 'Completed') {
        throw new Error(run.failure_reason || `Fabric job ended with status "${run.status}"`);
      }
      setResult((r) => ({ ...r, inserted: started.row_count }));
    } catch (err) {
      setError(err.message);
    } finally {
      setIsInserting(false);
      setInsertStatus(null);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
      <div className="bg-white rounded-xl shadow-xl w-full max-w-5xl max-h-[85vh] overflow-y-auto">
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200 sticky top-0 bg-white z-10">
          <div>
            <span className="font-semibold text-slate-800 flex items-center gap-2">
              <FlaskConical className="w-4 h-4 text-mastek-primary" /> Create Test Data
            </span>
            <p className="text-xs text-slate-400 mt-0.5">
              Cloning <span className="font-mono text-slate-600">{source.tableName}</span>&rsquo;s columns only
              &mdash; no real rows are ever read. Fill in the rows you need, then Finalize to download a CSV.
              You upload it wherever you need it &mdash; nothing is created on the server.
            </p>
          </div>
          <button onClick={onClose} className="p-1 hover:bg-slate-100 rounded-lg shrink-0">
            <X className="w-5 h-5 text-slate-500" />
          </button>
        </div>

        <div className="p-6">
          {result ? (
            <div className="space-y-4">
              <div className="flex items-start gap-2 text-sm text-mastek-success bg-mastek-success/10 border border-mastek-success/30 rounded-lg px-3 py-2.5">
                <CheckCircle2 className="w-4 h-4 shrink-0 mt-0.5" />
                <div>
                  <p className="font-medium">
                    CSV downloaded with {result.rowCount} row{result.rowCount === 1 ? '' : 's'}.
                  </p>
                  <p className="text-xs mt-0.5 text-mastek-success/80">
                    Nothing was created on the server &mdash; the file is yours to upload wherever you need it.
                  </p>
                </div>
              </div>
              {result.inserted != null && (
                <div className="flex items-start gap-2 text-sm text-mastek-success bg-mastek-success/10 border border-mastek-success/30 rounded-lg px-3 py-2.5">
                  <CheckCircle2 className="w-4 h-4 shrink-0 mt-0.5" />
                  <p className="font-medium">
                    Inserted {result.inserted} row{result.inserted === 1 ? '' : 's'} into the real Fabric table
                    &ldquo;{source.tableName}&rdquo;.
                  </p>
                </div>
              )}
              {error && (
                <div className="flex items-center gap-2 text-sm text-red-600">
                  <AlertCircle className="w-4 h-4 shrink-0" /> {error}
                </div>
              )}
              <div className="flex items-center gap-2">
                <button
                  onClick={handleDownloadAgain}
                  className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-mastek-primary border border-mastek-primary/40 rounded-lg hover:bg-mastek-primary/10"
                >
                  <Download className="w-4 h-4" />
                  Download again
                </button>
                {result.inserted == null && source.connectorId && (
                  <button
                    onClick={handleInsertIntoFabric}
                    disabled={isInserting}
                    title="Writes these generated rows directly into the real Fabric table - irreversible"
                    className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-red-600 rounded-lg hover:brightness-110 disabled:opacity-50"
                  >
                    {isInserting ? <Loader2 className="w-4 h-4 animate-spin" /> : <DatabaseZap className="w-4 h-4" />}
                    Insert into Fabric table
                  </button>
                )}
                {insertStatus && <span className="text-xs text-slate-500">{insertStatus}</span>}
                <button
                  onClick={onClose}
                  className="px-4 py-2 text-sm font-medium text-white bg-mastek-primary rounded-lg hover:brightness-110"
                >
                  Done
                </button>
              </div>
            </div>
          ) : (
            <>
              <div className="flex items-center justify-between mb-2 flex-wrap gap-2">
                <p className="text-xs font-medium text-slate-500">
                  {rows.length} row{rows.length === 1 ? '' : 's'} &mdash; {nonEmptyRows.length} with at least one value filled in
                </p>
                <div className="flex items-center gap-2">
                  <label className="flex items-center gap-1.5 text-xs font-medium text-slate-500">
                    Rows
                    <select
                      value={ROW_COUNT_OPTIONS.includes(rowCount) ? rowCount : ''}
                      onChange={(e) => changeRowCount(Number(e.target.value))}
                      title="Replaces the current draft with a fresh blank set at this size"
                      className="px-2 py-1 text-xs border border-slate-300 rounded-md focus:outline-none focus:ring-2 focus:ring-mastek-accent"
                    >
                      {!ROW_COUNT_OPTIONS.includes(rowCount) && <option value="">{rowCount} (custom)</option>}
                      {ROW_COUNT_OPTIONS.map((n) => <option key={n} value={n}>{n.toLocaleString()}</option>)}
                    </select>
                  </label>
                  <button
                    onClick={randomizeAllRows}
                    title="Fill every row with random values shaped to each column's type - not real data, just a fast starting point. Hand-edit whichever cells matter after."
                    className="flex items-center gap-1.5 px-2.5 py-1 text-xs font-medium text-mastek-primary border border-mastek-primary/40 rounded-md hover:bg-mastek-primary/10"
                  >
                    <Dices className="w-3.5 h-3.5" /> Add random values
                  </button>
                  <button
                    onClick={addRow}
                    className="flex items-center gap-1.5 px-2.5 py-1 text-xs font-medium text-mastek-primary bg-mastek-primary/10 rounded-md hover:bg-mastek-primary/20"
                  >
                    <Plus className="w-3.5 h-3.5" /> Add row
                  </button>
                </div>
              </div>

              {rows.length > MAX_EDITABLE_ROWS && (
                <p className="flex items-center gap-2 text-xs text-amber-700 bg-amber-50 border border-amber-200 rounded px-2.5 py-1.5 mb-2">
                  <AlertCircle className="w-3.5 h-3.5 shrink-0" />
                  Showing the first {MAX_EDITABLE_ROWS} of {rows.length.toLocaleString()} rows for hand-editing
                  &mdash; the rest were generated the same way by &ldquo;Add random values&rdquo; and are still
                  included in the download/insert.
                </p>
              )}

              <div className="border border-slate-200 rounded-lg overflow-x-auto max-h-[50vh] overflow-y-auto">
                <table className="w-full text-sm">
                  <thead className="text-left text-xs font-medium text-slate-400 border-b border-slate-100 sticky top-0 bg-white z-10">
                    <tr>
                      <th className="px-2 py-2 w-8">#</th>
                      {source.columns.map((c) => (
                        <th key={c.name} className="px-2 py-2 min-w-[9rem]">
                          <span className="block font-mono text-slate-600 truncate">{c.name}</span>
                          <span className="text-[10px] uppercase tracking-wider text-slate-400">{c.data_type}</span>
                        </th>
                      ))}
                      <th className="px-2 py-2 w-10" />
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100">
                    {rows.slice(0, MAX_EDITABLE_ROWS).map((row, i) => (
                      <tr key={i}>
                        <td className="px-2 py-1.5 text-xs text-slate-400 tabular-nums">{i + 1}</td>
                        {source.columns.map((c) => (
                          <td key={c.name} className="px-1.5 py-1">
                            <input
                              value={row[c.name] ?? ''}
                              onChange={(e) => updateCell(i, c.name, e.target.value)}
                              className="w-full px-2 py-1 text-sm font-mono border border-slate-200 rounded focus:outline-none focus:ring-2 focus:ring-mastek-accent"
                            />
                          </td>
                        ))}
                        <td className="px-2 py-1.5">
                          <div className="flex items-center gap-0.5">
                            <button
                              onClick={() => randomizeRow(i)}
                              title="Randomize just this row"
                              className="p-1 text-slate-400 hover:text-mastek-primary hover:bg-mastek-primary/10 rounded"
                            >
                              <Dices className="w-3.5 h-3.5" />
                            </button>
                            <button
                              onClick={() => removeRow(i)}
                              title="Remove this row"
                              className="p-1 text-slate-400 hover:text-red-600 hover:bg-red-50 rounded"
                            >
                              <Trash2 className="w-3.5 h-3.5" />
                            </button>
                          </div>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              {error && (
                <div className="flex items-center gap-2 mt-3 text-sm text-red-600">
                  <AlertCircle className="w-4 h-4 shrink-0" /> {error}
                </div>
              )}

              <div className="flex items-center justify-end gap-2 mt-5">
                <button
                  onClick={onClose}
                  className="px-4 py-2 text-sm font-medium text-slate-500 rounded-lg hover:bg-slate-100"
                >
                  Cancel
                </button>
                <button
                  onClick={handleFinalize}
                  disabled={nonEmptyRows.length === 0}
                  title={nonEmptyRows.length === 0 ? 'Fill in at least one row first' : undefined}
                  className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-mastek-primary rounded-lg hover:brightness-110 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  <FlaskConical className="w-4 h-4" />
                  Finalize & Download CSV
                </button>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
